apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-infra
  namespace: ${argocd_namespace}
spec:
  project: default

  sources:
    - repoURL: git@github.com:qianzhong516/fileops-app-manifests.git
      targetRevision: HEAD
      path: argocd
      kustomize: {}

    - repoURL: https://aws.github.io/eks-charts
      chart: aws-load-balancer-controller
      targetRevision: 3.3.0
      helm:
        releaseName: aws-load-balancer-controller
        namespace: kube-system
        values: |
          clusterName: fileops-cluster
          vpcId: ${vpc_id}
          region: ${region}

  destination:
    server: https://kubernetes.default.svc
    namespace: ${argocd_namespace}

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
