name: "Terraform Apply"
on:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: "janice-zhong"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

jobs:
  changes:
    name: "Detect changed stacks"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      eks: ${{ steps.filter.outputs.eks }}
      helm: ${{ steps.filter.outputs.helm }}
    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            cluster:
              - 'cluster/**'
            data:
              - 'data/**'
            platform-addons:
              - 'platform-addons/**'
            workloads:
              - 'workloads/**'

  apply-cluster:
    needs: changes
    permissions:
      contents: read
    if: needs.changes.outputs.cluster == 'true'
    uses: ./.github/workflows/terraform-apply-stack.yml
    with:
      stack: cluster
      workspace: janice-zhong-fileops-cluster
      directory: ./cluster
    secrets: inherit

  apply-data:
    needs: [changes, apply-cluster]
    permissions:
      contents: read
    if: |
      always() &&
      needs.changes.outputs.data == 'true' &&
      (needs.apply-cluster.result == 'success' || needs.apply-cluster.result == 'skipped')
    uses: ./.github/workflows/terraform-apply-stack.yml
    with:
      stack: data
      workspace: janice-zhong-fileops-data
      directory: ./data
    secrets: inherit

  apply-platform-addons:
    needs: [changes, apply-cluster]
    permissions:
      contents: read
      pull-requests: write
    if: |
      always() &&
      needs.changes.outputs.platform-addons == 'true' &&
      (needs.apply-cluster.result == 'success' || needs.apply-cluster.result == 'skipped')
    uses: ./.github/workflows/terraform-apply-stack.yml
    with:
      stack: platform-addons
      workspace: janice-zhong-fileops-platform-addons
      directory: ./platform-addons
    secrets: inherit

  apply-workloads:
    needs: [changes, apply-platform-addons, apply-data]
    permissions:
      contents: read
      pull-requests: write
    if: |
      always() &&
      needs.changes.outputs.workloads == 'true' &&
      (needs.apply-platform-addons.result == 'success' || needs.apply-platform-addons.result == 'skipped') &&
      (needs.apply-data.result == 'success' || needs.apply-data.result == 'skipped')
    uses: ./.github/workflows/terraform-apply-stack.yml
    with:
      stack: workloads
      workspace: janice-zhong-fileops-workloads
      directory: ./workloads
    secrets: inherit
